package coursesitegenerator;

/**
 * This class provides the properties that are needed to be loaded for
 * setting up To Do List Maker workspace controls including language-dependent
 * text.
 * 
 * @author Richard McKenna
 * @version 1.0
 */
public enum CourseSitePropertyType {

    
    /* THESE ARE THE NODES IN OUR APP */
    // FOR SIMPLE OK/CANCEL DIALOG BOXES
    CSG_OK_PROMPT,
    CSG_CANCEL_PROMPT,

    // THESE ARE FOR TEXT PARTICULAR TO THE APP'S WORKSPACE CONTROLS
    CSG_LEFT_PANE,
    CSG_TAS_HEADER_PANE,
    CSG_TAS_HEADER_LABEL,
    CSG_GRAD_UNDERGRAD_TAS_PANE,
    CSG_ALL_RADIO_BUTTON,
    CSG_GRAD_RADIO_BUTTON,
    CSG_UNDERGRAD_RADIO_BUTTON,
    CSG_TAS_HEADER_TEXT_FIELD,
    CSG_TAS_TABLE_VIEW,
    CSG_NAME_TABLE_COLUMN,
    CSG_EMAIL_TABLE_COLUMN,
    CSG_SLOTS_TABLE_COLUMN,
    CSG_TYPE_TABLE_COLUMN,

    CSG_ADD_TA_PANE,
    CSG_NAME_TEXT_FIELD,
    CSG_EMAIL_TEXT_FIELD,
    CSG_ADD_TA_BUTTON,

    CSG_RIGHT_PANE,
    CSG_OFFICE_HOURS_HEADER_PANE,
    CSG_OFFICE_HOURS_HEADER_LABEL,
    CSG_OFFICE_HOURS_TABLE_VIEW,
    CSG_START_TIME_TABLE_COLUMN,
    CSG_END_TIME_TABLE_COLUMN,
    CSG_MONDAY_TABLE_COLUMN,
    CSG_TUESDAY_TABLE_COLUMN,
    CSG_WEDNESDAY_TABLE_COLUMN,
    CSG_THURSDAY_TABLE_COLUMN,
    CSG_FRIDAY_TABLE_COLUMN,
    CSG_DAYS_OF_WEEK,
    CSG_FOOLPROOF_SETTINGS,
    
    // FOR THE EDIT DIALOG
    CSG_TA_EDIT_DIALOG,
    CSG_TA_DIALOG_GRID_PANE,
    CSG_TA_DIALOG_HEADER_LABEL, 
    CSG_TA_DIALOG_NAME_LABEL,
    CSG_TA_DIALOG_NAME_TEXT_FIELD,
    CSG_TA_DIALOG_EMAIL_LABEL,
    CSG_TA_DIALOG_EMAIL_TEXT_FIELD,
    CSG_TA_DIALOG_TYPE_LABEL,
    CSG_TA_DIALOG_TYPE_BOX,
    CSG_TA_DIALOG_GRAD_RADIO_BUTTON,
    CSG_TA_DIALOG_UNDERGRAD_RADIO_BUTTON,
    CSG_TA_DIALOG_OK_BOX,
    CSG_TA_DIALOG_OK_BUTTON, 
    CSG_TA_DIALOG_CANCEL_BUTTON, 
    
    // THESE ARE FOR ERROR MESSAGES PARTICULAR TO THE APP
    CSG_NO_TA_SELECTED_TITLE, CSG_NO_TA_SELECTED_CONTENT,
    
    CSG_SITE_TAB,
    CSG_SYLLABUS_TAB,
    CSG_MEETING_TAB,
    CSG_OFFICE_TAB,
    CSG_SCHEDULE_TAB,
    
    CSG_SITE_PANE,
    CSG_SYLLABUS_PANE,
    CSG_MEETING_PANE,
    CSG_OFFICE_PANE,
    CSG_SCHEDULE_PANE,
    
    CSG_SITE_BANNER_BOX,
    CSG_SITE_PAGES_BOX,
    CSG_SITE_STYLE_BOX,
    CSG_SITE_INSTRUCTOR_BOX,
    CSG_SITE_BANNER_LABEL,
    CSG_SITE_SUBJECT_LABEL,
    CSG_SITE_NUMBER_LABEL,
    CSG_SITE_SEMESTER_LABEL,
    CSG_SITE_YEAR_LABEL,
    CSG_SITE_TITLE_LABEL,
    CSG_SITE_EXPORTDIR_LABEL,
    
    CSG_SYLLABUS_DESCRIPTION_BOX,
    CSG_SYLLABUS_TOPICS_BOX,
    CSG_SYLLABUS_PREREQ_BOX,
    CSG_SYLLABUS_OUTCOMES_BOX,
    CSG_SYLLABUS_TEXTBOOKS_BOX,
    CSG_SYLLABUS_GRADEDCOMPONENTS_BOX,
    CSG_SYLLABUS_GRADINGNOTE_BOX,
    CSG_SYLLABUS_ACEDEMICDISHONESTY_BOX,
    CSG_SYLLABUS_SPECIALASSISTANCE_BOX,
    
    
    
    CSG_OFFICE_TA_PANE,
    CSG_START_TIME_COMBOBOX,
    CSG_START_TIME_OPTIONS,
    CSG_START_TIME_DEFAULT,
    CSG_START_TIME_LABEL,
    CSG_END_TIME_LABEL
}
